services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U airflow || exit 1"]
      interval: 15s
      retries: 5
    ports:
      - "5433:5432"
    restart: always

  scheduler:
    build:
      context: .
    command: poetry run airflow scheduler
    restart: on-failure
    # Memory limits to prevent system crashes - increased for translation tasks
    deploy:
      resources:
        limits:
          memory: 6G  # Increased from 3G for translation models
        reservations:
          memory: 2G  # Increased from 1G
    healthcheck:
      test: ["CMD-SHELL", "poetry run airflow jobs check --job-type SchedulerJob --local || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
      - social_media_tracker_db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - PYTHONPATH=/app:/app/data_pipeline
      - WAREHOUSE_HOST=${WAREHOUSE_HOST}
      - WAREHOUSE_PORT=${WAREHOUSE_PORT}
      - WAREHOUSE_DB=${WAREHOUSE_DB}
      - WAREHOUSE_USER=${WAREHOUSE_USER}
      - WAREHOUSE_PASSWORD=${WAREHOUSE_PASSWORD}
      - DBT_DB_PASSWORD=${DBT_DB_PASSWORD}
      - OLLAMA_HOST=${OLLAMA_HOST}
      # Memory optimization environment variables - removed offline settings to allow model downloads
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256
      - MALLOC_ARENA_MAX=1
      - OMP_NUM_THREADS=1
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
      - ./dbt_social_media_tracker:/app/airflow/dbt_social_media_tracker
      - /home/florent.bossart/.gcp_keys:/app/airflow/.gcp_keys
      - ./data_pipeline:/app/data_pipeline
      - ./llm_enrichment:/app/llm_enrichment
      - /var/run/docker.sock:/var/run/docker.sock

  webserver:
    build:
      context: .
    command: poetry run scripts/entrypoint.sh
    restart: on-failure
    # Memory limits for webserver
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      - postgres
      - scheduler
      - social_media_tracker_db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:$POSTGRES_PASSWORD@postgres:5432/db
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=airflow
      - PYTHONPATH=/app:/app/data_pipeline
      - WAREHOUSE_HOST=${WAREHOUSE_HOST}
      - WAREHOUSE_PORT=${WAREHOUSE_PORT}
      - WAREHOUSE_DB=${WAREHOUSE_DB}
      - WAREHOUSE_USER=${WAREHOUSE_USER}
      - WAREHOUSE_PASSWORD=${WAREHOUSE_PASSWORD}
      - DBT_DB_PASSWORD=${DBT_DB_PASSWORD}
      - OLLAMA_HOST=${OLLAMA_HOST}
    volumes:
      - ./dags:/app/airflow/dags
      - ./data:/app/airflow/data
      - ./logs:/app/airflow/logs
      - ./data_pipeline:/app/data_pipeline
      - ./llm_enrichment:/app/llm_enrichment
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  social_media_tracker_db:
    image: postgres:14
    environment:
      - POSTGRES_DB=social_db
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=${DBT_DB_PASSWORD}
    volumes:
      - warehousedata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d social_db -U dbt || exit 1"]
      interval: 15s
      retries: 5
    restart: always

  smt_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    ports:
      - "8000:8000"
    command: poetry run uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./data:/app/data
    depends_on:
      - social_media_tracker_db

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    environment:
      DBT_DB_PASSWORD: ${DBT_DB_PASSWORD}
      DBT_PROFILES_DIR: /usr/app/dbt_social_media_tracker
    volumes:
      - /home/florent.bossart/code/florent-bossart/social_media_tracker/dbt_social_media_tracker:/usr/app/dbt_social_media_tracker
    working_dir: /usr/app/dbt_social_media_tracker
    depends_on:
      - social_media_tracker_db
    # entrypoint: [ "tail", "-f", "/dev/null" ] # Keeps the container running for exec, or change for CLI usage

  streamlit_dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app
    environment:
      - WAREHOUSE_HOST=${WAREHOUSE_HOST}
      - WAREHOUSE_PORT=${WAREHOUSE_PORT}
      - WAREHOUSE_DB=${WAREHOUSE_DB}
      - WAREHOUSE_USER=${WAREHOUSE_USER}
      - WAREHOUSE_PASSWORD=${WAREHOUSE_PASSWORD}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - social_media_tracker_db
    restart: always

volumes:
  pgdata:
  warehousedata:
