version: 2

models:
  - name: artist_trends_summary
    description: "Summarizes trend analysis data for artists, joining with latest sentiment."
    columns:
      - name: artist_name
        description: "Name of the artist."
        tests:
          - not_null
      - name: mention_count
        description: "Number of times the artist was mentioned."
      - name: sentiment_score
        description: "Average sentiment score associated with the artist in trend data."
      - name: trend_strength
        description: "Calculated strength of the trend for the artist."
      - name: trend_direction
        description: "Direction of the trend (e.g., up, down, neutral)."
      - name: engagement_level
        description: "Level of engagement for the artist."
      - name: platforms
        description: "Platforms where the artist was mentioned."
      - name: latest_sentiment
        description: "The most recent overall sentiment for the artist from sentiment analysis."
      - name: sentiment_confidence
        description: "Confidence score of the latest sentiment."
      - name: first_seen
        description: "Timestamp when the artist trend was first observed."
      - name: last_seen
        description: "Timestamp when the artist trend was last observed."

  - name: daily_trends
    description: "Aggregates trend data on a daily basis."
    columns:
      - name: analysis_date
        description: "Date of the trend analysis."
        tests:
          - not_null
          - unique
      - name: unique_entities
        description: "Number of unique entities analyzed on this date."
      - name: avg_sentiment
        description: "Average sentiment score across all entities for this date."
      - name: avg_trend_strength
        description: "Average trend strength across all entities for this date."
      - name: trending_up
        description: "Count of entities trending upwards on this date."
      - name: trending_down
        description: "Count of entities trending downwards on this date."
      - name: trending_neutral
        description: "Count of entities with neutral trends on this date."

  - name: dashboard_summary
    description: "Provides a high-level summary for a dashboard, including counts and averages from various analytics stages."
    columns:
      - name: report_date
        description: "Date the report was generated."
      - name: total_extractions
        description: "Total number of entity extractions."
      - name: total_sentiments
        description: "Total number of sentiment analyses performed."
      - name: trending_up_count
        description: "Total number of entities currently trending upwards."
      - name: avg_sentiment
        description: "Overall average sentiment strength."
      - name: avg_confidence
        description: "Overall average confidence score from summarization metrics."
      - name: latest_analysis_date
        description: "Date of the most recent entity extraction."

  - name: pipeline_overview
    description: "Provides an overview of record counts, date ranges, and average confidence scores for each stage of the analytics pipeline."
    columns:
      - name: stage
        description: "Name of the analytics pipeline stage (e.g., entity_extraction, sentiment_analysis)."
        tests:
          - not_null
          - accepted_values:
              values: ['entity_extraction', 'sentiment_analysis', 'trend_analysis', 'summarization']
      - name: record_count
        description: "Number of records processed in this stage."
      - name: earliest_date
        description: "Earliest processing date for records in this stage."
      - name: latest_date
        description: "Latest processing date for records in this stage."
      - name: avg_confidence
        description: "Average confidence score for the records in this stage."

  - name: platform_sentiment_comparison
    description: "Compares sentiment metrics across different source platforms."
    columns:
      - name: source_platform
        description: "The social media platform or source of the comments."
        tests:
          - not_null
      - name: total_comments
        description: "Total number of comments analyzed from this platform."
      - name: avg_sentiment_strength
        description: "Average sentiment strength for comments from this platform."
      - name: positive_count
        description: "Number of comments with a positive sentiment from this platform."
      - name: neutral_count
        description: "Number of comments with a neutral sentiment from this platform."
      - name: negative_count
        description: "Number of comments with a negative sentiment from this platform."
      - name: positive_percentage
        description: "Percentage of comments with a positive sentiment from this platform."
