version: 2

sources:
  - name: analytics # This is the source name we'll use in ref() or source()
    schema: analytics # This is the actual schema in your database
    tables:
      - name: entity_extraction
      - name: sentiment_analysis
      - name: artist_trends
      - name: genre_trends
      - name: temporal_trends
      - name: trend_summaries
      - name: summarization_metrics
      - name: insights_summaries
      - name: insights_summary_overview
      - name: insights_summary_key_findings
      - name: insights_summary_artist_insights
      - name: wordcloud_data
      - name: trend_summary_top_genres

  - name: intermediate # Source for intermediate schema tables
    schema: intermediate # This is the actual intermediate schema in your database
    tables:
      - name: cleaned_reddit_comments
      - name: cleaned_reddit_posts
      - name: cleaned_youtube_comments
      - name: cleaned_youtube_videos
