dbt_social_media_tracker:
  target: dev
  outputs:
    dev:
      type: postgres
      host: social_media_tracker_db  # Use service name, not localhost
      user: dbt
      password: "{{ env_var('DBT_DB_PASSWORD') }}"
      port: 5432  # Inside Docker network
      dbname: social_db
      schema: raw
      threads: 4
