# Streamlit Configuration for Cloud Deployment

[global]
# Global configuration
# dataFrameSerialization option has been removed in newer Streamlit versions

[server]
# Server configuration for Docker/Hugging Face deployment
port = 7860
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Theme configuration for better appearance
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

# Streamlit Cloud specific optimizations
[client]
# Reduce memory usage for Streamlit Cloud
caching = true
showErrorDetails = true

[runner]
# Optimize for Streamlit Cloud performance
magicEnabled = false
installTracer = false
fixMatplotlib = false

[logger]
# Reduce logging overhead
level = "warning"

[deprecation]
# Disable deprecation warnings to reduce overhead
showfileUploaderEncoding = false
showPyplotGlobalUse = false
