# Streamlit Cloud Secrets Template
# Copy this content to your Streamlit Cloud app's secrets management

[database]
host = "db.swjvbxebxxfrrmmkdnyg.supabase.co"
port = 5432
database = "postgres"
username = "postgres"
password = "nYwH9g8I2J3ETrKS"

# Note: Replace the values above with your actual Supabase credentials
# You can find these in your Supabase project settings
